import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from "../components/Layout";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>taskManager | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout/>
    </div>
  )
}
