import Head from 'next/head'
import Layout from "../components/Layout";



export default function Home() {
    return (
        <div>
            <Head>
                <title>taskManager | Home</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <Layout>
                sonething
            </Layout>
        </div>
    )
}
